---
- name: Alacritty install
  hosts: localhost
  tasks:
    - name: Install alacritty via package manager
      become: true
      ansible.builtin.package:
        state: present
        name: alacritty

    - name: Link alacritty config file
      ansible.builtin.file:
        src: "{{ playbook_dir }}/alacritty.yml"
        dest: "{{ ansible_env.HOME }}/.config/alacritty/alacritty.yml"
        state: link

    - name: Get Roxo colorscheme file
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/roxo-theme/alacritty/main/colorscheme.yml
        dest: "{{ ansible_env.HOME }}/.config/alacritty/colorscheme.yml"
        mode: 0644
