---
- name: alacritty install
  hosts: localhost
  tasks:
    - name: install alacritty via package manager
      become: true
      package:
        state: present
        name: alacritty
    - name: exec setup script
      script: 
        cmd: ./setup.sh
