---
- name: Kubernetes packages
  hosts: localhost
  vars:
    tmp_dir_name: /tmp/k8s-tools-install
  tasks:
    - name: Create temporary dir
      ansible.builtin.file:
        path: "{{ tmp_dir_name }}"
        state: directory
        mode: 0700

    - name: Get arkade installation script
      ansible.builtin.get_url:
        url: https://get.arkade.dev
        dest: "{{ tmp_dir_name }}/arkade_install.sh"
        mode: 0755

    - name: Execute arkade installation script
      become: true
      changed_when: false
      ansible.builtin.shell:
        chdir: "{{ tmp_dir_name }}"
        cmd: ./arkade_install.sh
      args:
        executable: /bin/sh

    - name: Get k3d installation script
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh
        dest: "{{ tmp_dir_name }}/k3d_install.sh"
        mode: 0755

    - name: Execute k3d installation script
      become: true
      changed_when: false
      ansible.builtin.shell:
        chdir: "{{ tmp_dir_name }}"
        cmd: ./k3d_install.sh
      args:
        executable: /bin/bash

    - name: Install k9s
      become: true
      ansible.builtin.unarchive:
        src: https://github.com/derailed/k9s/releases/download/v0.32.5/k9s_Linux_amd64.tar.gz
        dest: /usr/bin
        list_files: true
        remote_src: true
        extra_opts:
          - "--add-file"
          - "k9s"

    - name: Get transparent skin for k9s
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/derailed/k9s/master/skins/transparent.yaml
        dest: "{{ ansible_env.HOME }}/.config/k9s/skin.yaml"
        mode: '0644'

    - name: Clean temporary dir
      ansible.builtin.file:
        path: "{{ tmp_dir_name }}"
        state: absent
