---
- name: Vim setup
  hosts: localhost
  tasks:
    - name: Install vim
      become: true
      ansible.builtin.package:
        name: vim
        state: present

    - name: Link vimrc file
      ansible.builtin.file:
        src: "{{ playbook_dir }}/vimrc"
        dest: "{{ ansible_env.HOME }}/.vimrc"
        state: "link"
