---
- name: vim setup
  hosts: localhost
  tasks:
    - name: Install vim
      become: true
      ansible.builtin.package:
        name: vim
        state: present

    - name: Install oh-my-zsh
      ansible.builtin.shell:
        cmd: |
            curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
            https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
      args:
        executable: /bin/sh

    - name: Link vimrc file
      ansible.builtin.file:
        src: "{{ playbook_dir }}/vimrc"
        dest: "{{ ansible_env.HOME }}/.vimrc"
        state: "link"
