---
- name: Devtools setup
  hosts: localhost
  vars:
    tmp_dir_name: /tmp/dev-tools-install
  tasks:
    - name: Create temporary dir
      ansible.builtin.file:
        path: "{{ tmp_dir_name }}"
        state: directory
        mode: 0700

    - name: Install system packages
      become: true
      ignore_errors: true  # noqa: ignore-errors
      ansible.builtin.package:
        state: present
        name:
          - ncurses
          - libffi
          - readline
          - tk

    - name: Get arkade installation script
      ansible.builtin.get_url:
        url: https://get.arkade.dev
        dest: "{{ tmp_dir_name }}/arkade_install.sh"
        mode: 0755

    - name: Execute arkade installation script
      become: true
      changed_when: false
      ansible.builtin.shell:
        chdir: "{{ tmp_dir_name }}"
        cmd: ./arkade_install.sh
      args:
        executable: /bin/sh

    - name: Get nvm installation script
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh
        dest: "{{ tmp_dir_name }}/nvm_install.sh"
        mode: 0755

    - name: Execute nvm installation script
      become: true
      changed_when: false
      ansible.builtin.shell:
        chdir: "{{ tmp_dir_name }}"
        cmd: ./nvm_install.sh
      args:
        executable: /bin/bash

    - name: Get pyenv installation script
      ansible.builtin.get_url:
        url: https://pyenv.run
        dest: "{{ tmp_dir_name }}/pyenv_install.sh"
        mode: 0755

    - name: Execute pyenv installation script
      become: true
      changed_when: false
      ansible.builtin.shell:
        chdir: "{{ tmp_dir_name }}"
        cmd: ./pyenv_install.sh
      args:
        executable: /bin/bash

    - name: Link ssh config
      ansible.builtin.file:
        src: "{{ playbook_dir }}/config/sshconfig"
        dest: "{{ ansible_env.HOME }}/.ssh/config"
        state: "link"
        force: true

    - name: Append gitconfig
      ansible.builtin.blockinfile:
        block: "{{ lookup('ansible.builtin.file', './config/gitconfig') }}"
        path: "{{ ansible_env.HOME }}/.gitconfig"

    - name: Clean temporary dir
      ansible.builtin.file:
        path: "{{ tmp_dir_name }}"
        state: absent
