---
- name: devtools setup
  hosts: localhost
  tasks:
    - name: install system packages
      become: true
      ignore_errors: true
      ansible.builtin.package:
        state: present
        name:
          - openssl
          - openssl-devel
          - zlib
          - zlib-devel
          - bzip2-devel
          - ncurses-devel
          - libffi
          - libffi-devel
          - readline
          - readline-devel
          - sqlite
          - sqlite-devel
          - tk
          - tk-devel
          - make
          - cmake
          - gcc
          - libevent-devel
          - git-delta
          - ripgrep
          - fzf

    - name: Install pyenv
      ansible.builtin.shell:
        cmd: curl https://pyenv.run | bash
      args:
        executable: /bin/bash

    - name: Install nvm
      ansible.builtin.shell:
        cmd: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
      args:
        executable: /bin/bash

    - name: Unarchive luarocks
      ansible.builtin.unarchive:
        src: https://luarocks.org/releases/luarocks-3.9.2.tar.gz
        dest: /tmp
        remote_src: true

    - name: Install luarocks
      become: true
      ansible.builtin.shell:
        chdir: /tmp/luarocks-3.9.2
        cmd: |
          ./configure --lua-version=5.4 --with-lua-include=/usr/include
          make
          make install

    - name: Append gitconfig
      ansible.builtin.blockinfile:
        block: "{{ lookup('ansible.builtin.file', './config/gitconfig') }}"
        path: "{{ ansible_env.HOME }}/.gitconfig"
