---
- name: Flatpak setup
  hosts: localhost
  tasks:
    - name: Add flathub repository
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: user

    - name: Install applications
      community.general.flatpak:
        name:
          - com.github.tchx84.Flatseal
          - io.beekeeperstudio.Studio
          - md.obsidian.Obsidian
          - com.jgraph.drawio.desktop
          - org.localsend.localsend_app
          - com.spotify.Client
          - com.rtosta.zapzap
