---
- name: Flatpak setup
  hosts: localhost
  tasks:
    - name: Add the flathub flatpak repository remote
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: user

    - name: Install packages
      community.general.flatpak:
        name:
          - com.github.tchx84.Flatseal
          - io.beekeeperstudio.Studio
          - rest.insomnia.Insomnia
          - md.obsidian.Obsidian
          - com.jgraph.drawio.desktop
          - io.podman_desktop.PodmanDesktop
          - com.spotify.Client
