---
- name: Dnf packages
  hosts: localhost
  tasks:
    - name: Add docker repository
      become: true
      changed_when: false
      ansible.builtin.shell:
        cmd: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
      args:
        executable: /bin/sh

    - name: Install 'Development tools' package group
      become: true
      ansible.builtin.dnf:
        name: '@Development tools'
        state: present

    - name: Install languages/packages
      become: true
      ansible.builtin.dnf:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - dnf-plugins-core
          - cargo
          - gcc
          - golang
          - erlang
          - elixir
          - lua
          - lua-devel
          - java-openjdk-headless
          - rust
          - containerd.io
          - podman
          - fuse-overlayfs
          - ansible
          - ansible-lint
          - ncurses
          - libffi
          - readline
          - tk
