require('plugins.noice')
require('plugins.telescope')
require('plugins.web-devicons')
require('plugins.nvim-tree')
require('plugins.barbecue')
require('plugins.lualine')
require('plugins.bufferline')
require('plugins.barbar')
require('plugins.nvim-cursorline')
require('plugins.gitsigns')
require('plugins.which-key')
require('plugins.nvim-cmp')
require('plugins.treesitter')
require('plugins.trouble')
require('plugins.autopairs')
require('plugins.copilot')
require('plugins.colorizer')
require('plugins.comment')
require('plugins.toggleterm')
require('plugins.markdown-preview')

-- lsp config
require('plugins.lsp.mason')
require('plugins.lsp.lspconfig')
require('plugins.lsp.lspsaga')
require('plugins.lsp.null-ls')
