---
- name: Code setup
  hosts: localhost
  tasks:
    - name: Install extensions
      ansible.builtin.script:
        cmd: "{{ playbook_dir }}/ext-install.sh"

    - name: Link settings file
      ansible.builtin.file:
        src: "{{ playbook_dir }}/settings.json"
        dest: "{{ ansible_env.HOME }}/.config/Code/User/settings.json"
        state: "link"

    - name: Link keybindings file
      ansible.builtin.file:
        src: "{{ playbook_dir }}/keybindings.json"
        dest: "{{ ansible_env.HOME }}/.config/Code/User/keybindings.json"
        state: "link"

    - name: Enable vsc marketplace
      ansible.builtin.file:
        src: "{{ playbook_dir }}/product.json"
        dest: "{{ ansible_env.HOME }}/.config/Code/product.json"
        state: "link"

    - name: Link custom vsicons
      ansible.builtin.file:
        src: "{{ playbook_dir }}/vsicons-custom-icons"
        dest: "{{ ansible_env.HOME }}/.config/Code/User/vsicons-custom-icons"
        state: "link"
