---
- name: Config setup
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Append gitconfig
      ansible.builtin.blockinfile:
        block: "{{ lookup('ansible.builtin.file', './gitconfig') }}"
        path: "{{ ansible_env.HOME }}/.gitconfig"

    - name: Copy ssh config
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/sshconfig"
        dest: "{{ ansible_env.HOME }}/.ssh/config"
        mode: '0644'

    - name: Chech if yamllint binary exists
      ansible.builtin.command: which yamllint
      changed_when: false
      failed_when: false
      register: yamllint_exists

    - name: Ensure yamllint directory
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.config/yamllint"
        state: "directory"
        mode: "0700"
      when: yamllint_exists.rc is defined

    - name: Link yamllint config
      ansible.builtin.file:
        src: "{{ playbook_dir }}/yamllint"
        dest: "{{ ansible_env.HOME }}/.config/yamllint/config"
        state: "link"
        force: true
      when: yamllint_exists.rc is defined

    - name: Ensure aws directory
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.aws"
        state: "directory"
        mode: "0700"

    - name: Copy aws config
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/aws/config"
        dest: "{{ ansible_env.HOME }}/.aws/config"
        mode: '0644'

    - name: Copy aws credentials
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/aws/credentials"
        dest: "{{ ansible_env.HOME }}/.aws/credentials"
        mode: '0644'

    - name: Link dnf config
      ansible.builtin.blockinfile:
        block: "{{ lookup('ansible.builtin.file', './dnf.conf') }}"
        path: "/etc/dnf/dnf.conf"
      when: ansible_os_family == 'RedHat'
