apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: playground
servers: 1  # control-plane
agents: 3  # workers
image: rancher/k3s:v1.27.3-k3s1
subnet: "172.28.0.0/16"
ports:
  - port: 8081:80
    nodeFilters:
      - loadbalancer
options:
  k3d:
    wait: true
    timeout: "60s"
  k3s:
    extraArgs:
      - arg: --disable=metrics-server
        nodeFilters:
          - server:*
    nodeLabels:
      - label: ingress-ready=true
        nodeFilters:
          - server:*
      - label: virtualization=true
        nodeFilters:
          - agent:2
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
  runtime:
    ulimits:
      - name: nofile
        soft: 26677
        hard: 26677
