apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: playground
servers: 1  # control-plane
agents: 2  # workers
image: rancher/k3s:v1.26.9-k3s1
registries:
  create:
    name: registry.localhost
    host: "0.0.0.0"
    hostPort: "5000"
options:
  k3d:
    wait: true
    timeout: "60s"
  k3s:
    extraArgs:
      - arg: --disable=metrics-server
        nodeFilters:
          - server:*
      - arg: --disable=traefik
        nodeFilters:
          - server:*
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
  runtime:
    ulimits:
      - name: nofile
        soft: 26677
        hard: 26677
