apiVersion: k3d.io/v1alpha5
kind: Simple
servers: 1 #  control-plane
agents: 2 #  workers
subnet: "172.20.0.0/16"
ports:
  - port: 8081:80
    nodeFilters:
      - server:0
    registries:
      create:
        name: registry.localhost
        host: "0.0.0.0"
        hostPort: "5000"
hostAliases:
  - ip: 172.20.0.1
    hostnames:
      - k8s.lb.local
options:
  k3d:
    wait: true
    timeout: "60s"
  k3s:
    extraArgs:
      - arg: --disable=metrics-server
        nodeFilters:
          - server:*
      - arg: --disable=traefik
        nodeFilters:
          - server:*
      - arg: --flannel-backend=none
        nodeFilters:
          - server:*
      - arg: --disable-network-policy
        nodeFilters:
          - server:*
    nodeLabels:
      - label: ingress-ready=true
        nodeFilters:
          - server:*
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
  runtime:
    ulimits:
      - name: nofile
        soft: 26677
        hard: 26677
