apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: quintal
servers: 1  # control-plane
agents: 3  # workers
registries:
  create:
    name: registry.localhost
    host: "0.0.0.0"
    hostPort: "5000"
options:
  k3d:
    wait: true
  kubeconfig:
    updateDefaultKubeconfig: true
  runtime:
    ulimits:
      - name: nofile
        soft: 26677
        hard: 26677
