---
- name: K8s setup
  hosts: localhost
  tasks:
    - name: Create temporary dir
      ansible.builtin.file:
        path: /tmp/k8s-install
        state: directory
        mode: 0700

    - name: Get kubectl binary
      become: true
      ansible.builtin.get_url:
        url: https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl
        dest: /usr/bin/kubectl
        mode: 0755

    - name: Get helm installation script
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        dest: /tmp/k8s-install/helm_install.sh
        mode: 0755

    - name: Execute helm installation script
      become: true
      changed_when: false
      ansible.builtin.shell:
        chdir: /tmp/k8s-install
        cmd: ./helm_install.sh
      args:
        executable: /bin/bash

    - name: Git clone kubens/kubectx repo
      ansible.builtin.git:
        repo: https://github.com/ahmetb/kubectx
        version: master
        dest: /tmp/k8s-install/kubectx
        clone: true

    - name: Set kubens/kubectx binaries
      become: true
      changed_when: false
      ansible.builtin.shell:
        chdir: /tmp/k8s-install/kubectx
        cmd: |
          mv ./kubectx /usr/local/bin
          mv ./kubens /usr/local/bin
      args:
        executable: /bin/sh

    - name: Clean temporary dir
      ansible.builtin.file:
        path: /tmp/k8s-install
        state: absent
