---
apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  namespace: crossplane-system
type: Opaque
stringData:
  creds: |
    [default]
    aws_access_key_id = foo
    aws_secret_access_key = bar
---
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: aws-localstack
spec:
  endpoint:
    services: [iam, s3, sqs, lambda]
    url:
      type: Static
      static: http://localstack.localstack.svc.cluster.local:4566
    hostnameImmutable: true
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: aws-secret
      key: creds
  skip_credentials_validation: true
  skip_metadata_api_check: true
  skip_requesting_account_id: true
  s3_use_path_style: true
