---
- name: ZSH setup
  hosts: localhost
  vars:
    tmp_dir_name: /tmp/zsh-install
  tasks:
    - name: Create temporary dir
      ansible.builtin.file:
        path: "{{ tmp_dir_name }}"
        state: directory
        mode: 0700

    - name: Install zsh
      become: true
      ansible.builtin.package:
        name: zsh
        state: present

    - name: Get omz installation script
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: "{{ tmp_dir_name }}/omz_install.sh"
        mode: 0755

    - name: Execute omz installation script
      become: true
      changed_when: false
      ansible.builtin.shell:
        chdir: "{{ tmp_dir_name }}"
        cmd: ./omz_install.sh
      args:
        executable: /bin/sh

    - name: Install autosuggestions plugin
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-autosuggestions.git
        version: master
        dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"

    - name: Install syntax highlighting plugin
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
        version: master
        dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"

    - name: Clone spaceship theme
      ansible.builtin.git:
        repo: https://github.com/spaceship-prompt/spaceship-prompt.git
        version: master
        dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/themes/spaceship-prompt"
        depth: 1

    - name: Link spaceship theme file
      ansible.builtin.file:
        src: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/themes/spaceship-prompt/spaceship.zsh-theme"
        dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/themes/spaceship.zsh-theme"
        state: "link"

    - name: Link zshrc file
      ansible.builtin.file:
        src: "{{ playbook_dir }}/zshrc"
        dest: "{{ ansible_env.HOME }}/.zshrc"
        state: "link"

    - name: Clean temporary dir
      ansible.builtin.file:
        path: "{{ tmp_dir_name }}"
        state: absent
