---
- name: Neovim install
  hosts: localhost
  tasks:
    - name: Install neovim
      become: true
      ansible.builtin.package:
        name: neovim
        state: present

    - name: Link nvim config
      ansible.builtin.file:
        src: "{{ playbook_dir }}/nvim"
        dest: "{{ ansible_env.HOME }}/.config/nvim"
        state: link
