---
- name: System packages
  hosts: localhost
  tasks:
    - name: Install system packages
      become: true
      ansible.builtin.package:
        state: present
        name:
          - openssl
          - make
          - cmake
          - gcc
          - git-delta
          - ripgrep
          - fzf
          - meld
          - htop
          - fzf
          - ffmpeg
          - tldr
          - bat
          - lsd
          - zlib
          - bzip2
          - tk
